version: '3'
services:
  movies:
    image: abdul303/moviesservice:latest
    ports:
        - "80-80"
    deploy:
      replicas: 3

  train:
    image: abdul303/trainservice:latest
    ports:
        - "81-80"
    deploy:
      replicas: 3

  dth:
    image: abdul303/dthservice:latest
    ports:
        - "82:80
    deploy:
      replicas: 3

  recharge:
    image: abdul303/rechargeservice:latest
    ports:
        - "83:80"
    deploy:
      replicas: 3
